### PR TITLE
feat: commitlint refactoring

### PR DESCRIPTION
**Pull request by qlimenoque**

### CODE REVIEW

**Comment by oxidmod** [comment]
Looks like I'm still have access to this repo =)

**Comment by qlimenoque** [comment]
> 
Thank you for letting us know. We'll check it

**Comment by qlimenoque** [comment]
@oxidmod this repository is public and you are watching its changes.
You can unwatch it and notifications will be disabled.

**Comment by oxidmod** [comment]
> @oxidmod this repository is public and you are watching its changes. You can unwatch it and notifications will be disabled.

Oh, I forgot that it is public repo. Thanks!

**Pull request closed without merging**
